""""Add_AikidoInformation_table"

Revision ID: 42a42b817f1f
Revises: 74e53df500fc
Create Date: 2025-11-14 15:01:11.957895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a42b817f1f'
down_revision = '74e53df500fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aikido_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aikido_type', sa.String(length=100), nullable=True),
    sa.Column('aikido_rank', sa.String(length=50), nullable=True),
    sa.Column('afsa_no', sa.String(length=50), nullable=True),
    sa.Column('aif_no', sa.String(length=50), nullable=True),
    sa.Column('honbu_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('certificate_no', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aikido_information')
    # ### end Alembic commands ###
